server:
  port: 1145
spring:
  security:
    jwt:
      key: abcdefjhijk
      expire: 7
  web:
    resources:
      static-locations: classpath:/static/
      add-mappings: true
  mvc:
    static-path-pattern: /**
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
#    user:
#      name: admin
#      password: 123456
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/jieban
    username: root
    password: 114514
    driver-class-name: com.mysql.cj.jdbc.Driver
file:
  upload:
    path: static/uploads/images/
